# Generated by Django 4.0.3 on 2022-04-08 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='Inn0v@tur3', max_length=16)),
                ('points', models.IntegerField(default=0)),
                ('status', models.BooleanField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredictGridApp.groups')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('option1', models.CharField(default=0, max_length=200)),
                ('option2', models.CharField(default=0, max_length=200)),
                ('option3', models.CharField(default=0, max_length=200)),
                ('option4', models.CharField(default=0, max_length=200)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredictGridApp.question')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredictGridApp.users')),
            ],
            options={
                'db_table': 'user_answer',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredictGridApp.question')),
            ],
            options={
                'db_table': 'option',
            },
        ),
    ]
