# Generated by Django 4.0.3 on 2022-04-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredictGridApp', '0003_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_id',
        ),
    ]
