# Generated by Django 4.0.3 on 2022-04-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PredictGridApp', '0004_remove_user_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PredictGridApp.groups'),
        ),
    ]
