# Generated by Django 4.0.3 on 2022-04-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PredictGridApp', '0006_alter_user_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PredictGridApp.groups'),
        ),
    ]
