# Generated by Django 4.0.3 on 2022-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictGridApp', '0007_alter_user_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_question',
            field=models.DateField(auto_now=True),
        ),
    ]
